#!/bin/bash -i
eval "$(conda shell.bash hook)"
conda activate bgtrainer

black .
ruff .
docformatter --in-place --recursive --black backgammon/*
mypy backgammon

coverage run -m pytest
coverage report
